// This code was generated by a compiler from scratch/cat.lang
// http://github.com/anthony-y/compiler
typedef signed   char s8;
typedef unsigned char u8;
typedef signed   short s16;
typedef unsigned short u16;
typedef signed   int s32;
typedef unsigned int u32;
typedef signed   long int s64;
typedef unsigned long int u64;
typedef float  f32;
typedef double f64;
typedef struct string {u8 *data; u64 length;} string;
typedef enum bool {false, true} bool;
#define cast 
#define NULL (void *)0

void __global_initializers();
static inline string __make_string(u8 *data, u64 length) {
    return (string){.data=data, .length=length};
}

string read_file(string path);
void compiler_main();
void print(string s);
string magic_os_proc(string _);
struct i;
struct i {
struct i* j;
} ;

string read_file(string path) {
string data = magic_os_proc(path);
struct i k;
k.j = NULL;
return path;
}
void __compiler_main() {
__global_initializers();
struct {
int a;
string b;
}  ms;
ms.a = 10;
string data = read_file(__make_string("cat.lang", 8));
print(data);
}

void __global_initializers() {
}
int main(int __argcount, char *__args[]) {
__compiler_main();
}
