// This code was generated by a compiler from scratch/concat.lang
// http://github.com/anthony-y/compiler
typedef signed   char s8;
typedef unsigned char u8;
typedef signed   short s16;
typedef unsigned short u16;
typedef signed   int s32;
typedef unsigned int u32;
typedef signed   long int s64;
typedef unsigned long int u64;
typedef float  f32;
typedef double f64;
typedef struct string {u8 *data; u64 length;} string;
typedef enum bool {false, true} bool;
#define cast 
#define NULL (void *)0

void __global_initializers();
static inline string __make_string(u8 *data, u64 length) {
    return (string){.data=data, .length=length};
}

void compiler_main();
string concat(string a, string b);
void puts(u8* s);
void free(void* ptr);
void* malloc(u64 size);
void memcpy(void* dest, void* src, u64 n);



void __compiler_main() {
__global_initializers();
string c = concat(__make_string("Hello, ", 9), __make_string("world\n", 9));
// defer'd statement;
puts(c.data);
free(c.data);
}

string concat(string a, string b) {
string out = __make_string("", 2);
out.length = a.length+b.length;
out.data = malloc(out.length);
memcpy(out.data, a.data, a.length);
memcpy(out.data+a.length, b.data, b.length);
return out;
}

void __global_initializers() {
}
int main(int __argcount, char *__args[]) {
__compiler_main();
}
