// This code was generated by a compiler from scratch/names.lang
// http://github.com/anthony-y/compiler
typedef signed   char s8;
typedef unsigned char u8;
typedef signed   short s16;
typedef unsigned short u16;
typedef signed   int s32;
typedef unsigned int u32;
typedef signed   long int s64;
typedef unsigned long int u64;
typedef float  f32;
typedef double f64;
typedef struct string {u8 *data; u64 length;} string;
typedef enum bool {false, true} bool;
#define cast 
#define NULL (void *)0

void __global_initializers();
static inline string __make_string(u8 *data, u64 length) {
    return (string){.data=data, .length=length};
}

void compiler_main();
void other(int k);
int i;
int zz;
int* pp;
string s;
string ss;
void ___main();
void puts(u8* s);
void free(void* ptr);
void* malloc(u64 size);
void* realloc(void* ptr, u64 size);
void printf(u8* fmt, ...);
void memcpy(void* dest, void* src, u64 n);
u8* c_string(string s);
string substring(string s, u64 up_to);
void free_substring(string s);



void __compiler_main() {
__global_initializers();
other(10);
printf(__make_string("H", 3).data);
}

void other(int k) {
if (k==10) {
return;
};
__compiler_main();
}

void ___main() {
zz = 1;
ss = __make_string("a", 3);
pp = NULL;
}

u8* c_string(string s) {
string s2 = substring(s, s.length);
return s2.data;
}

string substring(string s, u64 up_to) {
string sub;
sub.data = malloc(up_to+1);
memcpy(sub.data, s.data, up_to);
sub.data[up_to] = 0;
sub.length = up_to;
return sub;
}

void free_substring(string s) {
free(s.data);
}

void __global_initializers() {
i = -10;
zz = i;
pp = NULL;
s = __make_string("Hii", 5);
ss = s;
}
int main(int __argcount, char *__args[]) {
__compiler_main();
}
