// This code was generated by a compiler from scratch/title.lang
// http://github.com/anthony-y/compiler
typedef signed   char s8;
typedef unsigned char u8;
typedef signed   short s16;
typedef unsigned short u16;
typedef signed   int s32;
typedef unsigned int u32;
typedef signed   long int s64;
typedef unsigned long int u64;
typedef float  f32;
typedef double f64;
typedef struct string {const u8 *data; u64 length;} string;
typedef enum bool {false, true} bool;
#define cast 
#define NULL (void *)0

void __global_initializers();
static inline string __make_string(const u8 *data, u64 length) {
    return (string){.data=data, .length=length};
}

int puts(u8* s);
void compiler_main();
string msg;

void __compiler_main() {
    __global_initializers();
    int b = -1;
    int i = (cast(int)b);
    while (b<i) {
        b += 12;
        return;
    };
    int* my_ptr = &b;
    (*(my_ptr+1)) = 10;
    i = *my_ptr;
    puts(msg.data);
}

void __global_initializers() {
    msg = __make_string("hi", 2);
}
int main(int __argcount, char *__args[]) {
    __compiler_main();
}
