// This code was generated by a compiler from scratch/use.lang
// http://github.com/anthony-y/compiler
typedef signed   char s8;
typedef unsigned char u8;
typedef signed   short s16;
typedef unsigned short u16;
typedef signed   int s32;
typedef unsigned int u32;
typedef signed   long int s64;
typedef unsigned long int u64;
typedef float  f32;
typedef double f64;
typedef struct string {u8 *data; u64 length;} string;
typedef enum bool {false, true} bool;
#define cast 
#define NULL (void *)0

void __global_initializers();
static inline string __make_string(u8 *data, u64 length) {
    return (string){.data=data, .length=length};
}

void* malloc(u64 _);
void free(void* _);
void memcpy(void* dest, void* src, u64 n);
void puts(u8* _);
int c_str_length(u8* s);
u8* to_c_string(string s);
void compiler_main();



int c_str_length(u8* s) {
int len = 0;
return len;
}

u8* to_c_string(string s) {
u8* c_str = (cast(u8*)malloc(s.length+1));
memcpy(c_str, s.data, s.length);
c_str[s.length] = 0;
return c_str;
}

void __compiler_main() {
__global_initializers();
string name = __make_string("Anthony", 9);
string* i = &name;
bool a = !i;
u8* name_c = to_c_string(name);
int length = c_str_length(name_c);
puts(name_c);
free(name_c);
}

void __global_initializers() {
}
int main(int __argcount, char *__args[]) {
__compiler_main();
}
