// This code was generated by a compiler from scratch/using.lang
// http://github.com/anthony-y/compiler
typedef signed   char s8;
typedef unsigned char u8;
typedef signed   short s16;
typedef unsigned short u16;
typedef signed   int s32;
typedef unsigned int u32;
typedef signed   long int s64;
typedef unsigned long int u64;
typedef float  f32;
typedef double f64;
typedef struct string {u8 *data; u64 length;} string;
typedef enum bool {false, true} bool;
#define cast 
#define NULL (void *)0

void __global_initializers();
static inline string __make_string(u8 *data, u64 length) {
    return (string){.data=data, .length=length};
}

void compiler_main();
struct MyStruct;
void __MyStruct_initer(struct MyStruct*);

struct MyStruct {
	int seventeen;
};

void __MyStruct_initer(struct MyStruct* s) {
s->seventeen = 17;
}

void __compiler_main() {
__global_initializers();
struct MyStruct mine;
__MyStruct_initer(&mine);
;
int i = seventeen;
int seventeen = 17;
}

void __global_initializers() {
}
int main(int __argcount, char *__args[]) {
__compiler_main();
}
