// This code was generated by a compiler from demos/demo.lang
// http://github.com/anthony-y/compiler
typedef signed   char s8;
typedef unsigned char u8;
typedef signed   short s16;
typedef unsigned short u16;
typedef signed   int s32;
typedef unsigned int u32;
typedef signed   long int s64;
typedef unsigned long int u64;
typedef float  f32;
typedef double f64;
typedef struct string {u8 *data; u64 length;} string;
typedef enum bool {false, true} bool;
#define cast 
#define NULL (void *)0

void __global_initializers();
static inline string __make_string(u8 *data, u64 length) {
    return (string){.data=data, .length=length};
}

void compiler_main();
string scuffed_substring(string s, u64 up_to);
u8* c_string(string s);
void print(string s);
void memcpy(void* dest, void* src, u64 n);
void* malloc(u64 _);
void printf(u8* _1, ...);
void free(void* _);
void puts(u8* s);

void __compiler_main() {
__global_initializers();
string msg = __make_string("Hello, world!", 13);
string substring = scuffed_substring(msg, 5);
// defer'd statement;
print(msg);
print(substring);
u8* c_fmt = c_string(__make_string("%s", 2));
// defer'd statement;
printf(c_fmt, __make_string("printf kinda works\n", 20).data);
free(c_fmt);
free(substring.data);
}
string scuffed_substring(string s, u64 up_to) {
string sub;
sub.data = malloc(up_to+1);
memcpy(sub.data, s.data, up_to);
sub.data[up_to] = 0;
sub.length = up_to;
return sub;
}
u8* c_string(string s) {
string s2 = scuffed_substring(s, s.length);
return s2.data;
}
void print(string s) {
puts(s.data);
}

void __global_initializers() {
}
int main(int __argcount, char *__args[]) {
__compiler_main();
}
