// This code was generated by a compiler, from demos/imports.lang
// http://github.com/anthony-y/compiler
typedef signed   char s8;
typedef unsigned char u8;
typedef signed   short s16;
typedef unsigned short u16;
typedef signed   int s32;
typedef unsigned int u32;
typedef signed   long int s64;
typedef unsigned long int u64;
typedef float  f32;
typedef double f64;
typedef struct string {u8 *data; u64 length;} string;
typedef enum bool {false, true} bool;
#define cast 
#define NULL (void *)0

void __global_initializers();
static inline string __make_string(u8 *data, u64 length) {
    return (string){.data=data, .length=length};
}

string msg;
u64 len;
void compiler_main();
void free(void* ptr);
void* malloc(u64 size);
void* realloc(void* ptr, u64 size);
void printf(u8* fmt, ...);
void memcpy(void* dest, void* src, u64 n);
string substring(string s, u64 up_to);
struct Arena;
void __Arena_initer(struct Arena*);
u8* arena_alloc(struct Arena* a, u64 size);
void arena_free(struct Arena* a);
bool arena_maybe_grow(struct Arena* a, u64 desired_size);

struct Arena {
	bool fixed;
	int cursor;
	int capacity;
	u8* mem;
};

void __Arena_initer(struct Arena* s) {
s->fixed = true;
s->cursor = 0;
s->capacity = 2048;
s->mem = malloc(2048);
}

void __compiler_main() {
__global_initializers();
struct Arena arena;
__Arena_initer(&arena);
// defer'd statement;
u8* bytes = arena_alloc(&arena, len);
memcpy(bytes, msg.data, len);
bytes[len] = 0;
printf(__make_string("%s", 4).data, bytes);
arena_free(&arena);
}

string substring(string s, u64 up_to) {
string sub;
sub.data = malloc(up_to+1);
memcpy(sub.data, s.data, up_to);
sub.data[up_to] = 0;
sub.length = up_to;
return sub;
}

u8* arena_alloc(struct Arena* a, u64 size) {
if (!arena_maybe_grow(a, size)) {
return NULL;
};
u8* ret = a->mem+a->cursor;
a->cursor += size;
return ret;
}

void arena_free(struct Arena* a) {
free(a->mem);
a->fixed = false;
a->cursor = 0;
a->capacity = 0;
}

bool arena_maybe_grow(struct Arena* a, u64 desired_size) {
if (!a->fixed&&(a->cursor+desired_size)>a->capacity) {
a->capacity *= 2;
u8* tmp = (cast(u8*)realloc(a->mem, a->capacity));
if (!tmp) {
return false;
};
a->mem = tmp;
return true;
;
};
return true;
}

void __global_initializers() {
msg = __make_string("Arena allocator from another module\n", 39);
len = msg.length;
}
int main(int __argcount, char *__args[]) {
__compiler_main();
}
