// This code was generated by a compiler from demos/imports.lang
// http://github.com/anthony-y/compiler
typedef signed   char s8;
typedef unsigned char u8;
typedef signed   short s16;
typedef unsigned short u16;
typedef signed   int s32;
typedef unsigned int u32;
typedef signed   long int s64;
typedef unsigned long int u64;
typedef float  f32;
typedef double f64;
typedef struct string {u8 *data; u64 length;} string;
typedef enum bool {false, true} bool;
#define cast 
#define NULL (void *)0

void __global_initializers();
static inline string __make_string(u8 *data, u64 length) {
    return (string){.data=data, .length=length};
}

string msg;
u64 len;
void compiler_main();



void __compiler_main() {
__global_initializers();
struct Arena arena;
__Arena_initer(&arena);
arena.mem = malloc(arena.capacity);
// defer'd statement;
u8* bytes = arena_alloc(&arena, len+1);
memcpy(bytes, msg.data, len);
bytes[len] = 0;
printf(__make_string("%s", 4).data, bytes);
free(arena.mem);
}

void __global_initializers() {
msg = __make_string("Arena allocator from another module\n", 39);
len = msg.length;
}
int main(int __argcount, char *__args[]) {
__compiler_main();
}
